application: bicitacora
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media
  static_dir: media

- url: /
  script: bicitacora.app

- url: /estadisticas
  script: bicitacora.est